"""Added age to Promotion

Revision ID: 1d5c72ef4a81
Revises: 0cc4b668663e
Create Date: 2020-09-10 21:13:57.392536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5c72ef4a81'
down_revision = '0cc4b668663e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotion', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('transfer', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer', 'age')
    op.drop_column('promotion', 'age')
    # ### end Alembic commands ###
