"""renamed

Revision ID: 36c5b708e3d4
Revises: 1d5c72ef4a81
Create Date: 2020-09-15 20:56:39.406978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36c5b708e3d4'
down_revision = '1d5c72ef4a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('transfer_specification', sa.String(length=100), nullable=False))
    op.add_column('transfer', sa.Column('transfered_from', sa.String(length=50), nullable=False))
    op.drop_column('transfer', 'transfered_specification')
    op.drop_column('transfer', 'transformed_from')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('transformed_from', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('transfer', sa.Column('transfered_specification', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('transfer', 'transfered_from')
    op.drop_column('transfer', 'transfer_specification')
    # ### end Alembic commands ###
