"""accessibility table

Revision ID: 50e6734ef40f
Revises: 69537ed994eb
Create Date: 2020-12-20 17:46:59.922233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e6734ef40f'
down_revision = '69537ed994eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessibility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('assembly', sa.String(length=30), nullable=False),
    sa.Column('assembly_status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['user.member_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password_hash')
    )
    op.create_index(op.f('ix_accessibility_member_id'), 'accessibility', ['member_id'], unique=False)
    op.create_index(op.f('ix_accessibility_position'), 'accessibility', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accessibility_position'), table_name='accessibility')
    op.drop_index(op.f('ix_accessibility_member_id'), table_name='accessibility')
    op.drop_table('accessibility')
    # ### end Alembic commands ###
