"""Attendance Table

Revision ID: 69537ed994eb
Revises: 638b035a3cd8
Create Date: 2020-12-03 18:02:24.106563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69537ed994eb'
down_revision = '638b035a3cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('time_in', sa.String(length=6), nullable=False),
    sa.Column('time_out', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['user.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_event'), 'attendance', ['event'], unique=False)
    op.create_index(op.f('ix_attendance_member_id'), 'attendance', ['member_id'], unique=False)
    op.create_index(op.f('ix_attendance_status'), 'attendance', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_time_in'), 'attendance', ['time_in'], unique=False)
    op.create_index(op.f('ix_attendance_time_out'), 'attendance', ['time_out'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_time_out'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_time_in'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_status'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_member_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_event'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
