"""accessibility check

Revision ID: 0f39fe6dba85
Revises: 50e6734ef40f
Create Date: 2020-12-20 22:19:42.794529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f39fe6dba85'
down_revision = '50e6734ef40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accessibility', sa.Column('permission', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_accessibility_permission'), 'accessibility', ['permission'], unique=False)
    op.drop_index('ix_accessibility_position', table_name='accessibility')
    op.drop_column('accessibility', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accessibility', sa.Column('position', mysql.VARCHAR(length=50), nullable=False))
    op.create_index('ix_accessibility_position', 'accessibility', ['position'], unique=False)
    op.drop_index(op.f('ix_accessibility_permission'), table_name='accessibility')
    op.drop_column('accessibility', 'permission')
    # ### end Alembic commands ###
