"""Initial migrate

Revision ID: 40b136c21bbf
Revises: 
Create Date: 2020-07-27 22:04:33.489938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b136c21bbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.String(length=30), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('other_names', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('occupation', sa.String(length=50), nullable=False),
    sa.Column('contact_one', sa.String(length=14), nullable=False),
    sa.Column('contact_two', sa.String(length=14), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('marital_status', sa.String(length=10), nullable=False),
    sa.Column('church_affiliation', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('mode_of_communication', sa.String(length=6), nullable=False),
    sa.Column('address_line_one', sa.String(length=100), nullable=False),
    sa.Column('address_line_two', sa.String(length=100), nullable=False),
    sa.Column('digital_address', sa.String(length=15), nullable=False),
    sa.Column('region', sa.String(length=30), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', 'member_id'),
    sa.UniqueConstraint('password_hash')
    )
    op.create_index(op.f('ix_user_contact_one'), 'user', ['contact_one'], unique=False)
    op.create_index(op.f('ix_user_contact_two'), 'user', ['contact_two'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_member_id'), 'user', ['member_id'], unique=False)
    op.create_index(op.f('ix_user_other_names'), 'user', ['other_names'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_other_names'), table_name='user')
    op.drop_index(op.f('ix_user_member_id'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_contact_two'), table_name='user')
    op.drop_index(op.f('ix_user_contact_one'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
