"""birth registry added

Revision ID: 638b035a3cd8
Revises: 36c5b708e3d4
Create Date: 2020-09-15 22:14:47.418101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638b035a3cd8'
down_revision = '36c5b708e3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id_father', sa.String(length=20), nullable=False),
    sa.Column('member_id_mother', sa.String(length=20), nullable=False),
    sa.Column('child_name', sa.String(length=50), nullable=False),
    sa.Column('child_dob', sa.DateTime(), nullable=False),
    sa.Column('ceremony_date_time', sa.DateTime(), nullable=False),
    sa.Column('officiating_minister', sa.String(length=50), nullable=False),
    sa.Column('assembly', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_birth_child_name'), 'birth', ['child_name'], unique=False)
    op.create_index(op.f('ix_birth_member_id_father'), 'birth', ['member_id_father'], unique=False)
    op.create_index(op.f('ix_birth_member_id_mother'), 'birth', ['member_id_mother'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_birth_member_id_mother'), table_name='birth')
    op.drop_index(op.f('ix_birth_member_id_father'), table_name='birth')
    op.drop_index(op.f('ix_birth_child_name'), table_name='birth')
    op.drop_table('birth')
    # ### end Alembic commands ###
