"""deaths

Revision ID: 6d9f5e929157
Revises: 2abe34ec5efa
Create Date: 2020-09-01 21:59:51.580302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9f5e929157'
down_revision = '2abe34ec5efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('death',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('death_date', sa.DateTime(), nullable=False),
    sa.Column('burial_date', sa.DateTime(), nullable=False),
    sa.Column('place_of_burial', sa.String(length=50), nullable=False),
    sa.Column('officiating_minister', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['user.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_death_member_id'), 'death', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_death_member_id'), table_name='death')
    op.drop_table('death')
    # ### end Alembic commands ###
