"""Initial db migrate

Revision ID: 8353c3d24de9
Revises: 
Create Date: 2021-01-09 19:02:39.057367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8353c3d24de9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id_father', sa.String(length=20), nullable=False),
    sa.Column('member_id_mother', sa.String(length=20), nullable=False),
    sa.Column('child_name', sa.String(length=50), nullable=False),
    sa.Column('child_dob', sa.DateTime(), nullable=False),
    sa.Column('ceremony_date_time', sa.DateTime(), nullable=False),
    sa.Column('officiating_minister', sa.String(length=50), nullable=False),
    sa.Column('assembly', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_birth_child_name'), 'birth', ['child_name'], unique=False)
    op.create_index(op.f('ix_birth_member_id_father'), 'birth', ['member_id_father'], unique=False)
    op.create_index(op.f('ix_birth_member_id_mother'), 'birth', ['member_id_mother'], unique=False)
    op.create_table('dedication',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id_father', sa.String(length=20), nullable=False),
    sa.Column('member_id_mother', sa.String(length=20), nullable=False),
    sa.Column('child_name', sa.String(length=50), nullable=False),
    sa.Column('child_dob', sa.DateTime(), nullable=False),
    sa.Column('dedication_date_time', sa.DateTime(), nullable=False),
    sa.Column('officiating_minister', sa.String(length=50), nullable=False),
    sa.Column('assembly', sa.String(length=30), nullable=False),
    sa.Column('place_of_ceremony', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dedication_child_name'), 'dedication', ['child_name'], unique=False)
    op.create_index(op.f('ix_dedication_member_id_father'), 'dedication', ['member_id_father'], unique=False)
    op.create_index(op.f('ix_dedication_member_id_mother'), 'dedication', ['member_id_mother'], unique=False)
    op.create_table('rallies_and_conventions',
    sa.Column('cr_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cr_type', sa.String(length=30), nullable=False),
    sa.Column('cr_title', sa.String(length=100), nullable=False),
    sa.Column('start_date_time', sa.DateTime(), nullable=False),
    sa.Column('end_date_time', sa.DateTime(), nullable=False),
    sa.Column('assembly', sa.String(length=30), nullable=False),
    sa.Column('venue', sa.String(length=50), nullable=False),
    sa.Column('souls_won', sa.Integer(), nullable=False),
    sa.Column('head_count', sa.Integer(), nullable=False),
    sa.Column('mode_of_count', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('cr_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('other_names', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('occupation', sa.String(length=50), nullable=False),
    sa.Column('contact_phone_1', sa.String(length=14), nullable=False),
    sa.Column('contact_phone_2', sa.String(length=14), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('marital_status', sa.String(length=10), nullable=False),
    sa.Column('assembly', sa.String(length=30), nullable=False),
    sa.Column('ministry', sa.String(length=50), nullable=True),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('comm_email', sa.Integer(), nullable=False),
    sa.Column('comm_sms', sa.Integer(), nullable=False),
    sa.Column('comm_phone', sa.Integer(), nullable=False),
    sa.Column('address_line_1', sa.String(length=100), nullable=False),
    sa.Column('address_line_2', sa.String(length=100), nullable=False),
    sa.Column('digital_address_code', sa.String(length=15), nullable=False),
    sa.Column('region', sa.String(length=30), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', 'member_id'),
    sa.UniqueConstraint('password_hash')
    )
    op.create_index(op.f('ix_user_contact_phone_1'), 'user', ['contact_phone_1'], unique=False)
    op.create_index(op.f('ix_user_contact_phone_2'), 'user', ['contact_phone_2'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_member_id'), 'user', ['member_id'], unique=False)
    op.create_index(op.f('ix_user_other_names'), 'user', ['other_names'], unique=False)
    op.create_table('accessibility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('permission', sa.String(length=50), nullable=False),
    sa.Column('assembly', sa.String(length=30), nullable=False),
    sa.Column('assembly_status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['user.member_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password_hash')
    )
    op.create_index(op.f('ix_accessibility_member_id'), 'accessibility', ['member_id'], unique=False)
    op.create_index(op.f('ix_accessibility_permission'), 'accessibility', ['permission'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('time_in', sa.String(length=6), nullable=False),
    sa.Column('time_out', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['user.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_event'), 'attendance', ['event'], unique=False)
    op.create_index(op.f('ix_attendance_member_id'), 'attendance', ['member_id'], unique=False)
    op.create_index(op.f('ix_attendance_status'), 'attendance', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_time_in'), 'attendance', ['time_in'], unique=False)
    op.create_index(op.f('ix_attendance_time_out'), 'attendance', ['time_out'], unique=False)
    op.create_table('baptism',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('date_of_baptism', sa.DateTime(), nullable=False),
    sa.Column('place_of_baptism', sa.String(length=50), nullable=False),
    sa.Column('officiating_minister', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['user.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baptism_member_id'), 'baptism', ['member_id'], unique=False)
    op.create_table('death',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('death_date', sa.DateTime(), nullable=False),
    sa.Column('burial_date', sa.DateTime(), nullable=False),
    sa.Column('place_of_burial', sa.String(length=50), nullable=False),
    sa.Column('officiating_minister', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['user.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_death_member_id'), 'death', ['member_id'], unique=False)
    op.create_table('promotion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('present_portfolio', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('promoted_portfolio', sa.String(length=50), nullable=False),
    sa.Column('portfolio_specification', sa.String(length=80), nullable=False),
    sa.Column('promotion_date', sa.DateTime(), nullable=False),
    sa.Column('officiating_minister', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['user.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_member_id'), 'promotion', ['member_id'], unique=False)
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('transfered_from', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('transfered_to', sa.String(length=50), nullable=False),
    sa.Column('present_portfolio', sa.String(length=50), nullable=False),
    sa.Column('transfer_specification', sa.String(length=100), nullable=False),
    sa.Column('transfer_date', sa.DateTime(), nullable=False),
    sa.Column('officiating_minister', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['user.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_member_id'), 'transfer', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_member_id'), table_name='transfer')
    op.drop_table('transfer')
    op.drop_index(op.f('ix_promotion_member_id'), table_name='promotion')
    op.drop_table('promotion')
    op.drop_index(op.f('ix_death_member_id'), table_name='death')
    op.drop_table('death')
    op.drop_index(op.f('ix_baptism_member_id'), table_name='baptism')
    op.drop_table('baptism')
    op.drop_index(op.f('ix_attendance_time_out'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_time_in'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_status'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_member_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_event'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_accessibility_permission'), table_name='accessibility')
    op.drop_index(op.f('ix_accessibility_member_id'), table_name='accessibility')
    op.drop_table('accessibility')
    op.drop_index(op.f('ix_user_other_names'), table_name='user')
    op.drop_index(op.f('ix_user_member_id'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_contact_phone_2'), table_name='user')
    op.drop_index(op.f('ix_user_contact_phone_1'), table_name='user')
    op.drop_table('user')
    op.drop_table('rallies_and_conventions')
    op.drop_index(op.f('ix_dedication_member_id_mother'), table_name='dedication')
    op.drop_index(op.f('ix_dedication_member_id_father'), table_name='dedication')
    op.drop_index(op.f('ix_dedication_child_name'), table_name='dedication')
    op.drop_table('dedication')
    op.drop_index(op.f('ix_birth_member_id_mother'), table_name='birth')
    op.drop_index(op.f('ix_birth_member_id_father'), table_name='birth')
    op.drop_index(op.f('ix_birth_child_name'), table_name='birth')
    op.drop_table('birth')
    # ### end Alembic commands ###
